classdef LuminoseConstants
    methods (Static)

        function f = folders()
            f = struct('parentFolder', "C:\Users\harrislab\");
        end

        function f = addFolders()
            f = LuminoseConstants.folders();
            f.luminose_hf   = fullfile(f.parentFolder, "luminose_hf");
            f.data          = fullfile(f.parentFolder, "luminoseData");
            f.lib           = fullfile(f.parentFolder, "luminoseLib");
            f.matlab        = fullfile(f.parentFolder, "MATLAB");
            f.hamamatsu     = fullfile(f.parentFolder, "Hamamatsu");

            addpath(genpath(f.luminose_hf), genpath(f.data), genpath(f.lib), genpath(f.matlab), genpath(f.hamamatsu));
            savepath();
        end

        function bpod = addBpod()
            f = LuminoseConstants.addFolders();
            bpod = struct( ...
                'protocols', fullfile(f.luminose_hf, "protocols"), ...
                'protocolFile', "testGoNogo.m", ...
                'dataPath', fullfile(f.data, "behaviour") ...
            );
        end

        function olf = addOlfactometer()
            f = LuminoseConstants.addFolders();
            base = fullfile(f.luminose_hf, "olfactometer");
            olf = struct( ...
                'sampleRate', 10000, ...
                'acquisitionTime', 5, ...
                'pulseTime', 1, ...
                'backValveDelay', 0.05, ...
                'preSequenceTime', 0.5, ...
                'postSequenceTime', 0.5, ...
                'distanceFile', fullfile(base, "canberra_all.csv"), ...
                'mapFile', fullfile(base, "canberra_all_mds.csv"), ...
                'odourChemicalsFile', fullfile(base, "odour_chemicals.tsv"), ...
                'odourBottlesFile', fullfile(base, "odour_bottles.tsv"), ...
                'sequencesFile', fullfile(base, "sequences.tsv") ...
            );
            olf.backValves = struct(...
                'deviceID', "backValves", ...
                'channelID', "port0/line0:7, port0/line16:23", ...
                'measurementType', "Digital", ...
                'channelCount', 16 ...
            );
            olf.frontValves = struct(...
                'deviceID', "frontValves", ...
                'channelID', "port0/line0:15", ...
                'measurementType', "Digital", ...
                'channelCount', 16 ...
            );
            olf.syncTTL = struct(...
                'deviceID', "frontValves", ...
                'channelID', "port0/line16", ...
                'measurementType', "Digital", ...
                'channelCount', 1 ...
            );
            olf.inputTrigger = struct(...
                'deviceID', "frontValves", ...
                'channelID', "port0/line31", ...
                'measurementType', "Digital" ...
            );
        end

        function dmd = addDMD()
            f = LuminoseConstants.addFolders();
            dmd = struct( ...
                'mode', 3, ...
                'testImagePath', fullfile(f.parentFolder, "Documents", "DLPimages", "bullseye1920x1080_inv.bmp") ...
            );
        end

        function bonsai = addBonsai()
            bonsai = struct( ...
                'exePath', 'C:\Users\harrislab\AppData\Local\Bonsai\bonsai', ...
                'workflowPath', 'C:\Users\harrislab\luminose_hf\bonsai\BehaviourCamerasAcquisition.bonsai' ...
            );
        end

    end
end
