%% Get task settings
run taskSettings.m

%%
global BpodSystem % Imports the BpodSystem object to the function workspace

%% Assert HiFi module is present + USB-paired (via USB button on console GUI)
BpodSystem.assertModule('HiFi', 1); % The second argument (1) indicates that the HiFi module must be paired with its USB serial port

% Create an instance of the HiFi module
H = BpodHiFi(BpodSystem.ModuleUSB.HiFi1); % The argument is the name of the HiFi module's USB serial port (e.g. COM3)

%% Define parameters
S = BpodSystem.ProtocolSettings; % Load settings chosen in launch manager into current workspace as a struct called S

%% Run state machine

function [sma, S] = PrepareStateMachine(S, TrialTypes, currentTrial, currentTrialEvents)
% In this case, we don't need trial events to build the state machine - but
% they are available in currentTrialEvents.
S = BpodParameterGUI('sync', S); % Sync parameters with BpodParameterGUI plugin

% Setup state machine description
sma = NewStateMachine();

sma = AddState(sma, 'Name', 'TrialStart', ...
    'Timer', 0.2,...
    'StateChangeConditions', {'Tup', 'TriggerDMD'},...
    'OutputActions', {'BNC1', 'High'}); % Serial message #6 = 'Push' command, to make any newly loaded sounds current
sma = AddState(sma, 'Name', 'TriggerDMD', ...
    'Timer', 0,...
    'StateChangeConditions', {'Port2Out', 'EarlyWithdrawal', 'Tup', 'DeliverStimulus'},...
    'OutputActions', {'BNC1out'});
sma = AddState(sma, 'Name', 'DeliverStimulus', ...
    'Timer', S.GUI.SoundDuration,...
    'StateChangeConditions', {'Port2Out', 'EarlyWithdrawal', 'Tup', 'WaitForResponse'},...
    'OutputActions', stimulusOutput);
sma = AddState(sma, 'Name', 'WaitForResponse', ...
    'Timer', S.GUI.ResponseTime,...
    'StateChangeConditions', {'Port1In', leftPokeAction, 'Port3In', rightPokeAction, 'Tup', 'exit'},...
    'OutputActions', {}); 
sma = AddState(sma, 'Name', 'LeftRewardDelay', ...
    'Timer', S.GUI.RewardDelay,...
    'StateChangeConditions', {'Tup', 'LeftReward', 'Port1Out', 'CorrectEarlyWithdrawal'},...
    'OutputActions', {}); 
sma = AddState(sma, 'Name', 'RightRewardDelay', ...
    'Timer', S.GUI.RewardDelay,...
    'StateChangeConditions', {'Tup', 'RightReward', 'Port3Out', 'CorrectEarlyWithdrawal'},...
    'OutputActions', {}); 
sma = AddState(sma, 'Name', 'LeftReward', ...
    'Timer', leftValveTime,...
    'StateChangeConditions', {'Tup', 'DrinkingLeft'},...
    'OutputActions', {'ValveState', 1}); 
sma = AddState(sma, 'Name', 'RightReward', ...
    'Timer', rightValveTime,...
    'StateChangeConditions', {'Tup', 'DrinkingRight'},...
    'OutputActions', {'ValveState', 4}); 
sma = AddState(sma, 'Name', 'DrinkingLeft', ...
    'Timer', 0,...
    'StateChangeConditions', {'Condition1', 'DrinkingGrace'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'DrinkingRight', ...
    'Timer', 0,...
    'StateChangeConditions', {'Condition2', 'DrinkingGrace'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'DrinkingGrace', ...
    'Timer', 0.5,...
    'StateChangeConditions', {'Tup', 'TimeOutState', 'Port1In', '>back', 'Port3In', '>back'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'PunishTimeout', ...
    'Timer', S.GUI.ErrorDelay,...
    'StateChangeConditions', {'Tup', '>exit'},...
    'OutputActions', {'HiFi1', ['P' 2]});
sma = AddState(sma, 'Name', 'EarlyWithdrawal', ...
    'Timer', S.GUI.ErrorDelay,...
    'StateChangeConditions', {'Tup', '>exit'},...
    'OutputActions', {'HiFi1', ['P' 3]});
sma = AddState(sma, 'Name', 'CorrectEarlyWithdrawal', ...
    'Timer', 0,...
    'StateChangeConditions', {'Tup', 'TimeOutState'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'TimeOutState', ... % Record events while next trial's state machine is sent
    'Timer', 1,...
    'StateChangeConditions', {'Tup', '>exit'},...
    'OutputActions', {});